import React from 'react';
import { View, Text, ScrollView, StyleSheet, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams } from 'expo-router';
import { goBack } from '@/lib/ui/nav';
import Svg, { Path } from 'react-native-svg';
import { useTheme, useThemedStyles, type Theme } from '@/lib/design/theme';

interface Section {
  h?: string;
  p: string;
}
interface Topic {
  title: string;
  updated?: string;
  sections: Section[];
}

// Content mirrors the canonical legal site (apps/catchstack/legal/, generated by
// scripts/gen-legal.py) — same real facts: starving-effort / support@starving-effort.com,
// and accurate to Catchstack's actual behavior.
const SUPPORT = 'support@starving-effort.com';

const TOPICS: Record<string, Topic> = {
  disclaimer: {
    title: 'Disclaimer',
    sections: [
      { p: 'Prices shown in Catchstack are public, UNGRADED reference values aggregated from pokemontcg.io (Pokémon), Scryfall (Magic: The Gathering), and TCGplayer. They are reference figures only — not an appraisal, offer, or guarantee of value.' },
      { h: 'Ungraded reference only', p: 'Prices in this build are public ungraded reference values from pokemontcg.io and Scryfall. They do not reflect grade-specific (PSA / BGS / CGC) market value. Grade-aware pricing is on the roadmap once a usable data source is wired.' },
      { h: 'Not financial advice', p: 'Signals (momentum, near-high, vs. cost) are computed from public market data and are provided for information only. Nothing in Catchstack is financial advice.' },
      { h: 'Not affiliated', p: 'Catchstack is not affiliated with, endorsed by, or sponsored by Nintendo, The Pokémon Company, Wizards of the Coast, PSA, or TCGplayer. All product names and trademarks are the property of their respective owners.' },
    ],
  },
  about: {
    title: 'About & data sources',
    sections: [
      { p: 'Catchstack is a private record for your trading-card collection. Track what you own, watch its reference value over time, and keep an organized, exportable inventory.' },
      { h: 'Local-first', p: 'Your collection lives on your device. Catchstack works offline and refreshes reference prices when you have a connection.' },
      { h: 'Where prices come from', p: 'Reference values shown in this build are bundled with the app — a snapshot of public, ungraded figures from pokemontcg.io, Scryfall, and TCGplayer. Live price updates are planned for a future release. Reference figures are not an appraisal.' },
      { h: 'Card images', p: 'Card artwork is fetched from pokemontcg.io and Scryfall as a reference image. You can replace it with your own photo, which stays on your device.' },
      { p: `© 2026 starving-effort. Contact ${SUPPORT}.` },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    sections: [
      { p: 'Short version: no accounts, no tracking, no ads. Your collection stays on your device. The app fetches public card prices and images from pokemontcg.io and Scryfall.' },
      { h: 'What we collect', p: 'No personal information. Catchstack has no accounts and no user database — no name, email, phone, or location, and no analytics, advertising identifiers, or tracking.' },
      { h: 'Where your data lives', p: "Your collection — the cards you own, grades, cost, storage, notes, alerts, and any photos you add — is stored only in your device's local storage. It never leaves your device and we never see it." },
      { h: 'Network requests for card images', p: 'To show card artwork, Catchstack requests public images from pokemontcg.io (Pokémon) and Scryfall (Magic: The Gathering). These requests contain only the public card identifiers needed — never your name, your collection, or personal information. These providers may receive standard technical metadata (such as your IP address) under their own privacy policies. Reference prices in this build are bundled with the app; live price fetches are planned for a future update.' },
      { h: 'Camera & photos', p: 'If you choose a photo for a card, the photo is saved on your device as that card\'s image. Photos are never uploaded to us or any third party.' },
      { h: 'Purchases', p: "Optional Pro is handled entirely by Apple's App Store. We never see your name or payment details." },
      { h: 'Your control', p: 'Because everything is stored locally, deleting the app removes all stored data from your device.' },
      { h: 'Contact', p: SUPPORT },
    ],
  },
  terms: {
    title: 'Terms of Use',
    sections: [
      { h: 'Acceptance', p: 'By downloading or using Catchstack ("the App"), you agree to these Terms. If you do not agree, please do not use the App.' },
      { h: 'The App', p: 'The App is a personal record-keeping tool for trading-card collections. Reference values are public, ungraded market figures from pokemontcg.io, Scryfall, and TCGplayer, provided "as is" — not an appraisal, an offer, or a guarantee of value.' },
      { h: 'Not financial advice', p: 'Signals and price information are derived from public market data and provided for information only. Nothing in the App is financial, investment, or trading advice.' },
      { h: 'Purchases', p: "An optional Pro subscription may be offered through Apple's App Store. Purchases are processed by Apple; subscriptions auto-renew until cancelled and can be managed in your Apple ID settings. Apple's standard EULA applies." },
      { h: 'Third-party content & trademarks', p: 'Card data and images are provided by pokemontcg.io and Scryfall. All product names, card images, and trademarks belong to their respective owners. Catchstack is not affiliated with Nintendo, The Pokémon Company, Wizards of the Coast, PSA, or TCGplayer.' },
      { h: 'Disclaimer & liability', p: 'The App is provided without warranties of any kind. To the maximum extent permitted by law, we are not liable for any damages arising from use of the App.' },
      { h: 'Contact', p: SUPPORT },
    ],
  },
  contact: {
    title: 'Contact Us',
    sections: [
      { p: "Questions, feedback, or a data correction? We'd like to hear from you." },
      { h: 'Support', p: SUPPORT },
      { h: 'Response time', p: 'We aim to reply within a few business days.' },
    ],
  },
};

export default function InfoScreen() {
  const styles = useThemedStyles(makeStyles);
  const tokens = useTheme();
  const { topic } = useLocalSearchParams<{ topic: string }>();
  const data = (topic && TOPICS[topic]) || TOPICS.about;

  return (
    <SafeAreaView style={styles.screen} edges={['top']}>
      <View style={styles.navbar}>
        <TouchableOpacity style={styles.navbtn} onPress={() => goBack()} activeOpacity={0.7}>
          <Svg width={22} height={22} viewBox="0 0 24 24" fill="none"><Path d="M15 5l-7 7 7 7" stroke={tokens.color.textPrimary} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" /></Svg>
        </TouchableOpacity>
        <Text style={styles.navTitle} numberOfLines={1}>{data.title}</Text>
        <View style={styles.navbtn} />
      </View>

      <ScrollView style={{ flex: 1 }} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Text style={styles.h1}>{data.title}</Text>
        {data.sections.map((s, i) => (
          <View key={i} style={styles.section}>
            {s.h ? <Text style={styles.h2}>{s.h}</Text> : null}
            <Text style={styles.body}>{s.p}</Text>
          </View>
        ))}
        <Text style={styles.foot}>Catchstack 1.0.0</Text>
        <View style={{ height: tokens.space.xl }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const makeStyles = (tokens: Theme) => StyleSheet.create({
  screen: { flex: 1, backgroundColor: tokens.color.bg },
  navbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingTop: 8, paddingBottom: 8 },
  navbtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  navTitle: { flex: 1, textAlign: 'center', fontSize: 16, fontWeight: '600', letterSpacing: -0.3, color: tokens.color.textPrimary },
  content: { paddingHorizontal: 24, paddingBottom: 24, maxWidth: 440, width: '100%', alignSelf: 'center' },
  h1: { fontSize: 28, fontWeight: '700', letterSpacing: -0.8, color: tokens.color.textPrimary, paddingTop: 8, paddingBottom: 8 },
  section: { paddingTop: 18 },
  h2: { fontSize: 15, fontWeight: '700', letterSpacing: -0.2, color: tokens.color.textPrimary, paddingBottom: 6 },
  body: { fontSize: 14.5, lineHeight: 22, color: tokens.color.textSecondary, letterSpacing: -0.1 },
  foot: { fontSize: 12, color: tokens.color.textTertiary, paddingTop: 28 },
});
